export const endpoints = {
  overview: '/api/v1/dashboard/overview',
  portfolioOverview: '/api/v1/portfolio/overview',
  portfolioMetrics: '/api/v1/portfolio/metrics',
  portfolioPositions: '/api/v1/portfolio/positions',
  riskSnapshot: '/api/v1/risk/snapshot',
  monitoringSystem: '/api/v1/monitoring/system',
  alerts: '/api/v1/alerts',
  schedulerJobs: '/api/v1/scheduler/jobs',
  equityHistory: '/api/v1/analytics/equity-history',
  executionSummary: '/api/v1/command-center/execution/latest',
  commandCenterRuntimeLatest: '/api/v1/command-center/runtime/latest',
  commandCenterRuntimeRuns: '/api/v1/command-center/runtime/runs',
  commandCenterRuntimeIssues: '/api/v1/command-center/runtime/issues',
  commandCenterRuntimeRunReview: (runId: string) => `/api/v1/command-center/runtime/runs/${encodeURIComponent(runId)}/review`,
  commandCenterRuntimeIssueAcknowledge: (diagnosisCode: string) => `/api/v1/command-center/runtime/issues/${encodeURIComponent(diagnosisCode)}/acknowledge`,
  commandCenterRuntimeDebug: '/api/v1/command-center/debug/runtime',
  commandCenterRuntimeDebugByRun: (runId: string) => `/api/v1/command-center/debug/runtime?run_id=${encodeURIComponent(runId)}`,
  executionLatest: '/api/v1/execution/fills',
  executionPlannerLatest: '/api/v1/execution/planner/latest',
  executionViewLatest: '/api/v1/execution/view/latest',
  executionOrders: '/api/v1/execution/orders',
  executionFills: '/api/v1/execution/fills',
  executionStateLatest: '/api/v1/execution/state/latest',
  executionBlockReasonsLatest: '/api/v1/execution/block-reasons/latest',
  strategyRegistry: '/api/v1/strategy/registry',
  governanceApprovals: '/api/v1/governance/approvals',
  configCurrent: '/api/v1/config/current',
  alertAcknowledge: (id: string) => `/api/v1/alerts/${id}/acknowledge`,
  schedulerRun: (name: string) => `/api/v1/scheduler/jobs/${name}/run`,
  schedulerPause: (name: string) => `/api/v1/scheduler/jobs/${name}/pause`,
  schedulerResume: (name: string) => `/api/v1/scheduler/jobs/${name}/resume`,
  strategyStart: (id: string) => `/api/v1/control/start-strategy`,
  strategyStop: (id: string) => `/api/v1/control/stop-strategy`,
  commandCenterStrategyStart: '/api/v1/command-center/strategies/start',
  commandCenterStrategyStop: '/api/v1/command-center/strategies/stop',
  commandCenterStrategyRisk: '/api/v1/command-center/strategies/risk',
  commandCenterRiskPause: '/api/v1/command-center/risk/pause',
  commandCenterRiskResume: '/api/v1/command-center/risk/resume',
  commandCenterRiskKillSwitch: '/api/v1/command-center/risk/kill-switch',
  governanceApprove: (id: string) => `/api/v1/governance/approvals/${id}/approve`,
  governanceReject: (id: string) => `/api/v1/governance/approvals/${id}/reject`,
  configDraftSave: '/api/v1/config/draft/save',
  currentUser: '/api/v1/auth/me',
  auditLogs: '/api/v1/admin/audit-logs',
} as const;
